//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO_BJHX_EI_Green.Client.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRO_BJHX_EI_Green.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端已经开启，请双击托盘图标打开！.
        /// </summary>
        public static string ClientOpen {
            get {
                return ResourceManager.GetString("ClientOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认要删除此数据吗？.
        /// </summary>
        public static string ConfirmToDelete {
            get {
                return ResourceManager.GetString("ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认要锁定此数据吗？.
        /// </summary>
        public static string ConfirmToLock {
            get {
                return ResourceManager.GetString("ConfirmToLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认要重新发送吗？.
        /// </summary>
        public static string ConfirmToResend {
            get {
                return ResourceManager.GetString("ConfirmToResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认要重置该用户的密码吗？.
        /// </summary>
        public static string ConfirmToReset {
            get {
                return ResourceManager.GetString("ConfirmToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认要解锁此数据吗？.
        /// </summary>
        public static string ConfirmToUnLock {
            get {
                return ResourceManager.GetString("ConfirmToUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑失败.
        /// </summary>
        public static string EditFailed {
            get {
                return ResourceManager.GetString("EditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑成功.
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请您检查.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误代码.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误信息.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单信息已经存在.
        /// </summary>
        public static string ExistMenu {
            get {
                return ResourceManager.GetString("ExistMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据删除失败,请刷新页面.
        /// </summary>
        public static string FailedDeleting {
            get {
                return ResourceManager.GetString("FailedDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据获取失败,请刷新页面.
        /// </summary>
        public static string FailedLoading {
            get {
                return ResourceManager.GetString("FailedLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据锁定失败，请刷新页面.
        /// </summary>
        public static string FailedLocking {
            get {
                return ResourceManager.GetString("FailedLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码重置失败，请稍后再试.
        /// </summary>
        public static string FailedResetting {
            get {
                return ResourceManager.GetString("FailedResetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户权限设置失败,请稍候再试！.
        /// </summary>
        public static string FailedSettingUserPermissions {
            get {
                return ResourceManager.GetString("FailedSettingUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户角色设置失败,请稍候再试！.
        /// </summary>
        public static string FailedSettingUserRole {
            get {
                return ResourceManager.GetString("FailedSettingUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据解锁失败，请刷新页面.
        /// </summary>
        public static string FailedUnLocking {
            get {
                return ResourceManager.GetString("FailedUnLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段不匹配.
        /// </summary>
        public static string FieldMismatch {
            get {
                return ResourceManager.GetString("FieldMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认禁用.
        /// </summary>
        public static string IsLock {
            get {
                return ResourceManager.GetString("IsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确认启用.
        /// </summary>
        public static string IsUnLock {
            get {
                return ResourceManager.GetString("IsUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您选择要禁用的数据.
        /// </summary>
        public static string LockData {
            get {
                return ResourceManager.GetString("LockData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用失败.
        /// </summary>
        public static string LockFail {
            get {
                return ResourceManager.GetString("LockFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用成功.
        /// </summary>
        public static string LockSuccess {
            get {
                return ResourceManager.GetString("LockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择所属模块.
        /// </summary>
        public static string SelectModule {
            get {
                return ResourceManager.GetString("SelectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择月份.
        /// </summary>
        public static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您勾选要设置的权限.
        /// </summary>
        public static string SelectPermissionsToSet {
            get {
                return ResourceManager.GetString("SelectPermissionsToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您勾选要设置的角色！.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择角色类型.
        /// </summary>
        public static string SelectRoleType {
            get {
                return ResourceManager.GetString("SelectRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择您要删除的数据.
        /// </summary>
        public static string SelectToDelete {
            get {
                return ResourceManager.GetString("SelectToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您选择要锁定的数据.
        /// </summary>
        public static string SelectToLock {
            get {
                return ResourceManager.GetString("SelectToLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您选择要解锁的数据.
        /// </summary>
        public static string SelectToUnLock {
            get {
                return ResourceManager.GetString("SelectToUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您选择要启用的数据.
        /// </summary>
        public static string UnLockData {
            get {
                return ResourceManager.GetString("UnLockData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用失败.
        /// </summary>
        public static string UnlockFail {
            get {
                return ResourceManager.GetString("UnlockFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用成功.
        /// </summary>
        public static string UnLockSuccess {
            get {
                return ResourceManager.GetString("UnLockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名已经存在，请检查！.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
