//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO_ReceiptsInvMgr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRO_ReceiptsInvMgr.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限名称.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rollingFile.
        /// </summary>
        public static string AppenderName {
            get {
                return ResourceManager.GetString("AppenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用管理.
        /// </summary>
        public static string AppManger {
            get {
                return ResourceManager.GetString("AppManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO_ReceiptsInvMgr.Client.exe.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公共区.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxTool.ocx;config.dll;curllib.dll;kLoad.dll;libcurl.dll;libeay32.dll;libexpat.dll;RegDll.dll;Sec.dll;sqlite3.dll;ssleay32.dll.
        /// </summary>
        public static string AuxRelateFiles {
            get {
                return ResourceManager.GetString("AuxRelateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string BackSlash {
            get {
                return ResourceManager.GetString("BackSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载导入模板.
        /// </summary>
        public static string BtnDownload {
            get {
                return ResourceManager.GetString("BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锁定.
        /// </summary>
        public static string BtnLock {
            get {
                return ResourceManager.GetString("BtnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        public static string BtnModify {
            get {
                return ResourceManager.GetString("BtnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string BtnQuery {
            get {
                return ResourceManager.GetString("BtnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  搜 索.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string BtnSure {
            get {
                return ResourceManager.GetString("BtnSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解锁.
        /// </summary>
        public static string BtnUnlock {
            get {
                return ResourceManager.GetString("BtnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传文件.
        /// </summary>
        public static string BtnUpload {
            get {
                return ResourceManager.GetString("BtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string BtnView {
            get {
                return ResourceManager.GetString("BtnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.vpiaotong.com/do/bx.shtml.
        /// </summary>
        public static string bxLink {
            get {
                return ResourceManager.GetString("bxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改密码.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号：V{0}.
        /// </summary>
        public static string ClientVersion {
            get {
                return ResourceManager.GetString("ClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权所有.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pzb%@rjxc.
        /// </summary>
        public static string DbPwd {
            get {
                return ResourceManager.GetString("DbPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wtautoreg.
        /// </summary>
        public static string DeviceProcessName {
            get {
                return ResourceManager.GetString("DeviceProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceIoApi.
        /// </summary>
        public static string DeviceServiceProcName {
            get {
                return ResourceManager.GetString("DeviceServiceProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \PRO_ReceiptsInvMgr\Download\.
        /// </summary>
        public static string DownLoadPath {
            get {
                return ResourceManager.GetString("DownLoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dazhangfang.com/.
        /// </summary>
        public static string dzfLink {
            get {
                return ResourceManager.GetString("dzfLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Soft\PRO_ReceiptsInvMgr.Client.exe.
        /// </summary>
        public static string ExePath {
            get {
                return ResourceManager.GetString("ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoveR1314.
        /// </summary>
        public static string FwkpDbPwd {
            get {
                return ResourceManager.GetString("FwkpDbPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aisino.Framework.Startup.
        /// </summary>
        public static string FwkpProcessName {
            get {
                return ResourceManager.GetString("FwkpProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/fp-btn-add.png.
        /// </summary>
        public static string IcoAddApp {
            get {
                return ResourceManager.GetString("IcoAddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon10.png.
        /// </summary>
        public static string IcoAppDown {
            get {
                return ResourceManager.GetString("IcoAppDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon10-hover.png.
        /// </summary>
        public static string IcoAppDownHover {
            get {
                return ResourceManager.GetString("IcoAppDownHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PRO_ReceiptsInvMgr.Client;component/Resources/image/btn02.png.
        /// </summary>
        public static string IcoDown {
            get {
                return ResourceManager.GetString("IcoDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PRO_ReceiptsInvMgr.Client;component/Resources/image/bg03.png.
        /// </summary>
        public static string IcoDownNetError {
            get {
                return ResourceManager.GetString("IcoDownNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PRO_ReceiptsInvMgr.Client;component/Resources/image/bg04.png.
        /// </summary>
        public static string IcoDownNoExist {
            get {
                return ResourceManager.GetString("IcoDownNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/restart-btn.jpg.
        /// </summary>
        public static string IcoDownRestart {
            get {
                return ResourceManager.GetString("IcoDownRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PRO_ReceiptsInvMgr.Client;component/Resources/image/bg05.png.
        /// </summary>
        public static string IcoDriverNotExist {
            get {
                return ResourceManager.GetString("IcoDriverNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon60.png.
        /// </summary>
        public static string IcoFpcyApp {
            get {
                return ResourceManager.GetString("IcoFpcyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type-dian.png.
        /// </summary>
        public static string IcoFpcyDian {
            get {
                return ResourceManager.GetString("IcoFpcyDian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type_03.png.
        /// </summary>
        public static string IcoFpcyHYYS {
            get {
                return ResourceManager.GetString("IcoFpcyHYYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type_06.png.
        /// </summary>
        public static string IcoFpcyJDC {
            get {
                return ResourceManager.GetString("IcoFpcyJDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type-juan.png.
        /// </summary>
        public static string IcoFpcyJuan {
            get {
                return ResourceManager.GetString("IcoFpcyJuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type-pu.png.
        /// </summary>
        public static string IcoFpcyPu {
            get {
                return ResourceManager.GetString("IcoFpcyPu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type-tong.png.
        /// </summary>
        public static string IcoFpcyTong {
            get {
                return ResourceManager.GetString("IcoFpcyTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/image/cy-type-zhuan.png.
        /// </summary>
        public static string IcoFpcyZhuan {
            get {
                return ResourceManager.GetString("IcoFpcyZhuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon-jxgl-01.png.
        /// </summary>
        public static string IcoJxglApp {
            get {
                return ResourceManager.GetString("IcoJxglApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_03.png.
        /// </summary>
        public static string IcoJxglGxrz {
            get {
                return ResourceManager.GetString("IcoJxglGxrz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_03.png.
        /// </summary>
        public static string IcoJxglGxrzActive {
            get {
                return ResourceManager.GetString("IcoJxglGxrzActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_12.png.
        /// </summary>
        public static string IcoJxglRzqd {
            get {
                return ResourceManager.GetString("IcoJxglRzqd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_12.png.
        /// </summary>
        public static string IcoJxglRzqdActive {
            get {
                return ResourceManager.GetString("IcoJxglRzqdActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_10.png.
        /// </summary>
        public static string IcoJxglYqyj {
            get {
                return ResourceManager.GetString("IcoJxglYqyj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_10.png.
        /// </summary>
        public static string IcoJxglYqyjActive {
            get {
                return ResourceManager.GetString("IcoJxglYqyjActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon08.png.
        /// </summary>
        public static string IcoPrintDriver {
            get {
                return ResourceManager.GetString("IcoPrintDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon08-hover.png.
        /// </summary>
        public static string IcoPrintDriverHover {
            get {
                return ResourceManager.GetString("IcoPrintDriverHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/image/icon09-hover.png.
        /// </summary>
        public static string IcoUninstallHover {
            get {
                return ResourceManager.GetString("IcoUninstallHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWKPInstall.exe.
        /// </summary>
        public static string InstallPackageName {
            get {
                return ResourceManager.GetString("InstallPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票软件 V2.1.20.160425.01 安装.
        /// </summary>
        public static string InstallWindowName {
            get {
                return ResourceManager.GetString("InstallWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AISINO JSP shuikong USB Device.
        /// </summary>
        public static string JSPDeviceName {
            get {
                return ResourceManager.GetString("JSPDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金报税盘税务数字证书驱动.
        /// </summary>
        public static string JSPTool {
            get {
                return ResourceManager.GetString("JSPTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \DefaultApp\进项税发票管理软件.
        /// </summary>
        public static string JXAppPath {
            get {
                return ResourceManager.GetString("JXAppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \DefaultApp\进项税发票管理软件\进项税发票管理软件.exe.
        /// </summary>
        public static string JXAppStartPath {
            get {
                return ResourceManager.GetString("JXAppStartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fpdk.bjsat.gov.cn/.
        /// </summary>
        public static string JXTokenUrl {
            get {
                return ResourceManager.GetString("JXTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string LegSearch {
            get {
                return ResourceManager.GetString("LegSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\票智宝.exe.
        /// </summary>
        public static string LinkName {
            get {
                return ResourceManager.GetString("LinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\localhost.
        /// </summary>
        public static string LocalHost {
            get {
                return ResourceManager.GetString("LocalHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作.
        /// </summary>
        public static string LogAction {
            get {
                return ResourceManager.GetString("LogAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string LogContent {
            get {
                return ResourceManager.GetString("LogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面.
        /// </summary>
        public static string LogController {
            get {
                return ResourceManager.GetString("LogController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检索结束时间.
        /// </summary>
        public static string LogEnded {
            get {
                return ResourceManager.GetString("LogEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注销.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检索开始时间.
        /// </summary>
        public static string LogStarted {
            get {
                return ResourceManager.GetString("LogStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作日期.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作人.
        /// </summary>
        public static string LogUser {
            get {
                return ResourceManager.GetString("LogUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户手册.pdf.
        /// </summary>
        public static string ManualFilename {
            get {
                return ResourceManager.GetString("ManualFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单导航.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块名称.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://icanhazip.com/.
        /// </summary>
        public static string NetIcanhazip {
            get {
                return ResourceManager.GetString("NetIcanhazip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NISEC_SafeToolkit 1.0.8.7 安装.
        /// </summary>
        public static string NISECInstallName {
            get {
                return ResourceManager.GetString("NISECInstallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53520764.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.vpiaotong.com/.
        /// </summary>
        public static string ptLink {
            get {
                return ResourceManager.GetString("ptLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 550.
        /// </summary>
        public static string RandomValue {
            get {
                return ResourceManager.GetString("RandomValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\fwkp.exe.
        /// </summary>
        public static string RegeditFwkp {
            get {
                return ResourceManager.GetString("RegeditFwkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\skfpkprj\skfpkprj.
        /// </summary>
        public static string RegeditSkp {
            get {
                return ResourceManager.GetString("RegeditSkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System\CurrentControlSet\Services\CDRom.
        /// </summary>
        public static string RegiditAutoRunKey1 {
            get {
                return ResourceManager.GetString("RegiditAutoRunKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows\CurrentVersion\Policies\Explorer.
        /// </summary>
        public static string RegiditAutoRunKey2 {
            get {
                return ResourceManager.GetString("RegiditAutoRunKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NISEC TCG-01 USB Device.
        /// </summary>
        public static string SKPDeviceName {
            get {
                return ResourceManager.GetString("SKPDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NISEC_SafeToolkit.
        /// </summary>
        public static string SKPTool {
            get {
                return ResourceManager.GetString("SKPTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \PRO_ReceiptsInvMgr\logs\.
        /// </summary>
        public static string SoftLogPath {
            get {
                return ResourceManager.GetString("SoftLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.chinatax.gov.cn/.
        /// </summary>
        public static string taxLink {
            get {
                return ResourceManager.GetString("taxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwkp\{0}.{1}\Automation\InvAutomation.exe.
        /// </summary>
        public static string UpdateFwkpConfigPath {
            get {
                return ResourceManager.GetString("UpdateFwkpConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fwkp.aisino.com.
        /// </summary>
        public static string UpdateServer {
            get {
                return ResourceManager.GetString("UpdateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/soap/envelope/.
        /// </summary>
        public static string WebServiceSoapUri {
            get {
                return ResourceManager.GetString("WebServiceSoapUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://InMemoryDocument.xps.
        /// </summary>
        public static string XpsUri {
            get {
                return ResourceManager.GetString("XpsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RJXC PZB USB Device.
        /// </summary>
        public static string ZFTDeviceName {
            get {
                return ResourceManager.GetString("ZFTDeviceName", resourceCulture);
            }
        }
    }
}
