//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO_ReceiptsInvMgr.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRO_ReceiptsInvMgr.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称 的本地化字符串。
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rollingFile 的本地化字符串。
        /// </summary>
        public static string AppenderName {
            get {
                return ResourceManager.GetString("AppenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用管理 的本地化字符串。
        /// </summary>
        public static string AppManger {
            get {
                return ResourceManager.GetString("AppManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRO_ReceiptsInvMgr.Client.exe 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共区 的本地化字符串。
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuxTool.ocx;config.dll;curllib.dll;kLoad.dll;libcurl.dll;libeay32.dll;libexpat.dll;RegDll.dll;Sec.dll;sqlite3.dll;ssleay32.dll 的本地化字符串。
        /// </summary>
        public static string AuxRelateFiles {
            get {
                return ResourceManager.GetString("AuxRelateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 / 的本地化字符串。
        /// </summary>
        public static string BackSlash {
            get {
                return ResourceManager.GetString("BackSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {4A4CA7ED-3ECD-4267-9922-BAC9B40447BB}_is1 的本地化字符串。
        /// </summary>
        public static string BASETool {
            get {
                return ResourceManager.GetString("BASETool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载导入模板 的本地化字符串。
        /// </summary>
        public static string BtnDownload {
            get {
                return ResourceManager.GetString("BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        public static string BtnLock {
            get {
                return ResourceManager.GetString("BtnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string BtnModify {
            get {
                return ResourceManager.GetString("BtnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string BtnQuery {
            get {
                return ResourceManager.GetString("BtnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  搜 索 的本地化字符串。
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string BtnSure {
            get {
                return ResourceManager.GetString("BtnSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        public static string BtnUnlock {
            get {
                return ResourceManager.GetString("BtnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string BtnUpload {
            get {
                return ResourceManager.GetString("BtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string BtnView {
            get {
                return ResourceManager.GetString("BtnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.vpiaotong.com/do/bx.shtml 的本地化字符串。
        /// </summary>
        public static string bxLink {
            get {
                return ResourceManager.GetString("bxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号：V{0} 的本地化字符串。
        /// </summary>
        public static string ClientVersion {
            get {
                return ResourceManager.GetString("ClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权所有 的本地化字符串。
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pzb%@rjxc 的本地化字符串。
        /// </summary>
        public static string DbPwd {
            get {
                return ResourceManager.GetString("DbPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wtautoreg 的本地化字符串。
        /// </summary>
        public static string DeviceProcessName {
            get {
                return ResourceManager.GetString("DeviceProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceIoApi 的本地化字符串。
        /// </summary>
        public static string DeviceServiceProcName {
            get {
                return ResourceManager.GetString("DeviceServiceProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \PRO_ReceiptsInvMgr\Download\ 的本地化字符串。
        /// </summary>
        public static string DownLoadPath {
            get {
                return ResourceManager.GetString("DownLoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.dazhangfang.com/ 的本地化字符串。
        /// </summary>
        public static string dzfLink {
            get {
                return ResourceManager.GetString("dzfLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}Soft\PRO_ReceiptsInvMgr.Client.exe 的本地化字符串。
        /// </summary>
        public static string ExePath {
            get {
                return ResourceManager.GetString("ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoveR1314 的本地化字符串。
        /// </summary>
        public static string FwkpDbPwd {
            get {
                return ResourceManager.GetString("FwkpDbPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aisino.Framework.Startup 的本地化字符串。
        /// </summary>
        public static string FwkpProcessName {
            get {
                return ResourceManager.GetString("FwkpProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/fp-btn-add.png 的本地化字符串。
        /// </summary>
        public static string IcoAddApp {
            get {
                return ResourceManager.GetString("IcoAddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon10.png 的本地化字符串。
        /// </summary>
        public static string IcoAppDown {
            get {
                return ResourceManager.GetString("IcoAppDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon10-hover.png 的本地化字符串。
        /// </summary>
        public static string IcoAppDownHover {
            get {
                return ResourceManager.GetString("IcoAppDownHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /PRO_ReceiptsInvMgr.Client;component/Resources/image/btn02.png 的本地化字符串。
        /// </summary>
        public static string IcoDown {
            get {
                return ResourceManager.GetString("IcoDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /PRO_ReceiptsInvMgr.Client;component/Resources/image/bg03.png 的本地化字符串。
        /// </summary>
        public static string IcoDownNetError {
            get {
                return ResourceManager.GetString("IcoDownNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /PRO_ReceiptsInvMgr.Client;component/Resources/image/bg04.png 的本地化字符串。
        /// </summary>
        public static string IcoDownNoExist {
            get {
                return ResourceManager.GetString("IcoDownNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/restart-btn.jpg 的本地化字符串。
        /// </summary>
        public static string IcoDownRestart {
            get {
                return ResourceManager.GetString("IcoDownRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /PRO_ReceiptsInvMgr.Client;component/Resources/image/bg05.png 的本地化字符串。
        /// </summary>
        public static string IcoDriverNotExist {
            get {
                return ResourceManager.GetString("IcoDriverNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon60.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyApp {
            get {
                return ResourceManager.GetString("IcoFpcyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type-dian.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyDian {
            get {
                return ResourceManager.GetString("IcoFpcyDian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type_03.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyHYYS {
            get {
                return ResourceManager.GetString("IcoFpcyHYYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type_06.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyJDC {
            get {
                return ResourceManager.GetString("IcoFpcyJDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type-juan.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyJuan {
            get {
                return ResourceManager.GetString("IcoFpcyJuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type-pu.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyPu {
            get {
                return ResourceManager.GetString("IcoFpcyPu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type-tong.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyTong {
            get {
                return ResourceManager.GetString("IcoFpcyTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Resources/image/cy-type-zhuan.png 的本地化字符串。
        /// </summary>
        public static string IcoFpcyZhuan {
            get {
                return ResourceManager.GetString("IcoFpcyZhuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon-jxgl-01.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglApp {
            get {
                return ResourceManager.GetString("IcoJxglApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_03.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglGxrz {
            get {
                return ResourceManager.GetString("IcoJxglGxrz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_03.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglGxrzActive {
            get {
                return ResourceManager.GetString("IcoJxglGxrzActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_12.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglRzqd {
            get {
                return ResourceManager.GetString("IcoJxglRzqd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_12.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglRzqdActive {
            get {
                return ResourceManager.GetString("IcoJxglRzqdActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_08.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglSmrz {
            get {
                return ResourceManager.GetString("IcoJxglSmrz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_08.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglSmrzActive {
            get {
                return ResourceManager.GetString("IcoJxglSmrzActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon_10.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglYqyj {
            get {
                return ResourceManager.GetString("IcoJxglYqyj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/JXGL/pzb-tab-icon-active_10.png 的本地化字符串。
        /// </summary>
        public static string IcoJxglYqyjActive {
            get {
                return ResourceManager.GetString("IcoJxglYqyjActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon08.png 的本地化字符串。
        /// </summary>
        public static string IcoPrintDriver {
            get {
                return ResourceManager.GetString("IcoPrintDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon08-hover.png 的本地化字符串。
        /// </summary>
        public static string IcoPrintDriverHover {
            get {
                return ResourceManager.GetString("IcoPrintDriverHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://application:,,,/Resources/image/icon09-hover.png 的本地化字符串。
        /// </summary>
        public static string IcoUninstallHover {
            get {
                return ResourceManager.GetString("IcoUninstallHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FWKPInstall.exe 的本地化字符串。
        /// </summary>
        public static string InstallPackageName {
            get {
                return ResourceManager.GetString("InstallPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开票软件 V2.1.20.160425.01 安装 的本地化字符串。
        /// </summary>
        public static string InstallWindowName {
            get {
                return ResourceManager.GetString("InstallWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AISINO JSP shuikong USB Device 的本地化字符串。
        /// </summary>
        public static string JSPDeviceName {
            get {
                return ResourceManager.GetString("JSPDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金报税盘税务数字证书驱动 的本地化字符串。
        /// </summary>
        public static string JSPTool {
            get {
                return ResourceManager.GetString("JSPTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \DefaultApp\进项税发票管理软件 的本地化字符串。
        /// </summary>
        public static string JXAppPath {
            get {
                return ResourceManager.GetString("JXAppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \DefaultApp\进项税发票管理软件\进项税发票管理软件.exe 的本地化字符串。
        /// </summary>
        public static string JXAppStartPath {
            get {
                return ResourceManager.GetString("JXAppStartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://fpdk.bjsat.gov.cn/ 的本地化字符串。
        /// </summary>
        public static string JXTokenUrl {
            get {
                return ResourceManager.GetString("JXTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询条件 的本地化字符串。
        /// </summary>
        public static string LegSearch {
            get {
                return ResourceManager.GetString("LegSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}\票智宝.exe 的本地化字符串。
        /// </summary>
        public static string LinkName {
            get {
                return ResourceManager.GetString("LinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \\localhost 的本地化字符串。
        /// </summary>
        public static string LocalHost {
            get {
                return ResourceManager.GetString("LocalHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作 的本地化字符串。
        /// </summary>
        public static string LogAction {
            get {
                return ResourceManager.GetString("LogAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string LogContent {
            get {
                return ResourceManager.GetString("LogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面 的本地化字符串。
        /// </summary>
        public static string LogController {
            get {
                return ResourceManager.GetString("LogController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索结束时间 的本地化字符串。
        /// </summary>
        public static string LogEnded {
            get {
                return ResourceManager.GetString("LogEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索开始时间 的本地化字符串。
        /// </summary>
        public static string LogStarted {
            get {
                return ResourceManager.GetString("LogStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日期 的本地化字符串。
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        public static string LogUser {
            get {
                return ResourceManager.GetString("LogUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户手册.pdf 的本地化字符串。
        /// </summary>
        public static string ManualFilename {
            get {
                return ResourceManager.GetString("ManualFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单导航 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://icanhazip.com/ 的本地化字符串。
        /// </summary>
        public static string NetIcanhazip {
            get {
                return ResourceManager.GetString("NetIcanhazip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NISEC_SafeToolkit 1.0.8.7 安装 的本地化字符串。
        /// </summary>
        public static string NISECInstallName {
            get {
                return ResourceManager.GetString("NISECInstallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 53520764 的本地化字符串。
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.vpiaotong.com/ 的本地化字符串。
        /// </summary>
        public static string ptLink {
            get {
                return ResourceManager.GetString("ptLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 550 的本地化字符串。
        /// </summary>
        public static string RandomValue {
            get {
                return ResourceManager.GetString("RandomValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\fwkp.exe 的本地化字符串。
        /// </summary>
        public static string RegeditFwkp {
            get {
                return ResourceManager.GetString("RegeditFwkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOFTWARE\skfpkprj\skfpkprj 的本地化字符串。
        /// </summary>
        public static string RegeditSkp {
            get {
                return ResourceManager.GetString("RegeditSkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System\CurrentControlSet\Services\CDRom 的本地化字符串。
        /// </summary>
        public static string RegiditAutoRunKey1 {
            get {
                return ResourceManager.GetString("RegiditAutoRunKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 的本地化字符串。
        /// </summary>
        public static string RegiditAutoRunKey2 {
            get {
                return ResourceManager.GetString("RegiditAutoRunKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NISEC TCG-01 USB Device 的本地化字符串。
        /// </summary>
        public static string SKPDeviceName {
            get {
                return ResourceManager.GetString("SKPDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NISEC_SafeToolkit 的本地化字符串。
        /// </summary>
        public static string SKPTool {
            get {
                return ResourceManager.GetString("SKPTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \ 的本地化字符串。
        /// </summary>
        public static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \PRO_ReceiptsInvMgr\logs\ 的本地化字符串。
        /// </summary>
        public static string SoftLogPath {
            get {
                return ResourceManager.GetString("SoftLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.chinatax.gov.cn/ 的本地化字符串。
        /// </summary>
        public static string taxLink {
            get {
                return ResourceManager.GetString("taxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fwkp\{0}.{1}\Automation\InvAutomation.exe 的本地化字符串。
        /// </summary>
        public static string UpdateFwkpConfigPath {
            get {
                return ResourceManager.GetString("UpdateFwkpConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://fwkp.aisino.com 的本地化字符串。
        /// </summary>
        public static string UpdateServer {
            get {
                return ResourceManager.GetString("UpdateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://schemas.xmlsoap.org/soap/envelope/ 的本地化字符串。
        /// </summary>
        public static string WebServiceSoapUri {
            get {
                return ResourceManager.GetString("WebServiceSoapUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack://InMemoryDocument.xps 的本地化字符串。
        /// </summary>
        public static string XpsUri {
            get {
                return ResourceManager.GetString("XpsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RJXC PZB USB Device 的本地化字符串。
        /// </summary>
        public static string ZFTDeviceName {
            get {
                return ResourceManager.GetString("ZFTDeviceName", resourceCulture);
            }
        }
    }
}
