//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRO_ReceiptsInvMgr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRO_ReceiptsInvMgr.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取注册表失败： 获取权限错误.
        /// </summary>
        public static string AdministratorFailed {
            get {
                return ResourceManager.GetString("AdministratorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise\Advertise.html.
        /// </summary>
        public static string Advertise {
            get {
                return ResourceManager.GetString("Advertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告加载失败：.
        /// </summary>
        public static string AdvertiseFail {
            get {
                return ResourceManager.GetString("AdvertiseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载应用图标异常.
        /// </summary>
        public static string AppIcoError {
            get {
                return ResourceManager.GetString("AppIcoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}已安装成功.
        /// </summary>
        public static string AppInstallSuccess {
            get {
                return ResourceManager.GetString("AppInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尚未开通该应用.
        /// </summary>
        public static string AppNotOpen {
            get {
                return ResourceManager.GetString("AppNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该应用已超出使用期限.
        /// </summary>
        public static string AppOverTime {
            get {
                return ResourceManager.GetString("AppOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}已升级成功.
        /// </summary>
        public static string AppUpdateSuccess {
            get {
                return ResourceManager.GetString("AppUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxTool.ocx组件注册失败.
        /// </summary>
        public static string AuxToolRegistFail {
            get {
                return ResourceManager.GetString("AuxToolRegistFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查盒子连接状态异常.
        /// </summary>
        public static string BoxStateError {
            get {
                return ResourceManager.GetString("BoxStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clsid 不应该为空.
        /// </summary>
        public static string CheckClassId {
            get {
                return ResourceManager.GetString("CheckClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验码不能为空.
        /// </summary>
        public static string CheckCodeNotEmpty {
            get {
                return ResourceManager.GetString("CheckCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查盒子连接状态异常.
        /// </summary>
        public static string CheckDiskStateFail {
            get {
                return ResourceManager.GetString("CheckDiskStateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检查开票软件初始化....
        /// </summary>
        public static string CheckFreeInitTip {
            get {
                return ResourceManager.GetString("CheckFreeInitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票软件正在运行，无法打开进项发票管理应用。请退出开票软件后重试.
        /// </summary>
        public static string CheckFwkpTip {
            get {
                return ResourceManager.GetString("CheckFwkpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检查当前接入的开票设备....
        /// </summary>
        public static string CheckInvoiceDeviceTip {
            get {
                return ResourceManager.GetString("CheckInvoiceDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进项税发票管理软件正在运行，无法打开开票软件。请退出进项税发票管理软件后重试.
        /// </summary>
        public static string CheckJXTip {
            get {
                return ResourceManager.GetString("CheckJXTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查纳税人{0}.{1}开票软件升级失败：.
        /// </summary>
        public static string CheckShFwkpUpdateFailed {
            get {
                return ResourceManager.GetString("CheckShFwkpUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查当前接入的开票设备异常：.
        /// </summary>
        public static string CheckTaxDeviceError {
            get {
                return ResourceManager.GetString("CheckTaxDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查自动升级版本异常！.
        /// </summary>
        public static string CheckVersion {
            get {
                return ResourceManager.GetString("CheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file 不应该为空.
        /// </summary>
        public static string ChekckRegistry {
            get {
                return ResourceManager.GetString("ChekckRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端已经开启，请双击托盘图标打开！.
        /// </summary>
        public static string ClientOpen {
            get {
                return ResourceManager.GetString("ClientOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端升级异常：.
        /// </summary>
        public static string ClientUpdateError {
            get {
                return ResourceManager.GetString("ClientUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxTool组件调用失败！.
        /// </summary>
        public static string ComFailed {
            get {
                return ResourceManager.GetString("ComFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接服务器失败，请稍候重试！.
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接服务器失败.
        /// </summary>
        public static string ConnectFail {
            get {
                return ResourceManager.GetString("ConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化：创建数据库：.
        /// </summary>
        public static string CreateDataBase {
            get {
                return ResourceManager.GetString("CreateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建桌面快捷方式失败.
        /// </summary>
        public static string CreateDeskLinkError {
            get {
                return ResourceManager.GetString("CreateDeskLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在创建桌面快捷方式....
        /// </summary>
        public static string CreateLinkTip {
            get {
                return ResourceManager.GetString("CreateLinkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化数据库失败.
        /// </summary>
        public static string DataFail {
            get {
                return ResourceManager.GetString("DataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库加密失败：.
        /// </summary>
        public static string DBEncryptFail {
            get {
                return ResourceManager.GetString("DBEncryptFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解密{0}接口Content异常：.
        /// </summary>
        public static string DecodeFailed {
            get {
                return ResourceManager.GetString("DecodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除旧盘信息失败：.
        /// </summary>
        public static string DeleteAuthorizeFail {
            get {
                return ResourceManager.GetString("DeleteAuthorizeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RJXC PZB USB Device.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载{0}财税软件失败.
        /// </summary>
        public static string DownAppFail {
            get {
                return ResourceManager.GetString("DownAppFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 下载失败，MD5校验不通过.
        /// </summary>
        public static string DownFail {
            get {
                return ResourceManager.GetString("DownFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载最新版开票软件失败.
        /// </summary>
        public static string DownFwkpError {
            get {
                return ResourceManager.GetString("DownFwkpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现新版本，是否升级？.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5校验失败，文件已删除.
        /// </summary>
        public static string DownloadMd5Fail {
            get {
                return ResourceManager.GetString("DownloadMd5Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载OCX组件异常：.
        /// </summary>
        public static string DownOCXErrorMsg {
            get {
                return ResourceManager.GetString("DownOCXErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载OCX组件失败.
        /// </summary>
        public static string DownOcxFail {
            get {
                return ResourceManager.GetString("DownOcxFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载OCX组件异常,请查看是否网络连接正常。.
        /// </summary>
        public static string DownOcxFailTips {
            get {
                return ResourceManager.GetString("DownOcxFailTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号{0}开始下载....
        /// </summary>
        public static string DownStart {
            get {
                return ResourceManager.GetString("DownStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常信息：.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在正在下载的任务，是否关闭？.
        /// </summary>
        public static string ExitDownTask {
            get {
                return ResourceManager.GetString("ExitDownTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序关闭异常：.
        /// </summary>
        public static string ExitError {
            get {
                return ResourceManager.GetString("ExitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确定要退出吗？.
        /// </summary>
        public static string ExitMsg {
            get {
                return ResourceManager.GetString("ExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该纳税人已超出使用期限，请联系运维人员处理。.
        /// </summary>
        public static string ExpireTip {
            get {
                return ResourceManager.GetString("ExpireTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你单位于{0}认证的专用发票{1}份。其中认证相符的专用发票{2}份，税额{3}元，无法认证的专用发票0份，税额0.00元。请将认证相符的专用发票抵扣联与本通知书一起装订成册，作为纳税检查的备查资料。.
        /// </summary>
        public static string ExportJXJgContent {
            get {
                return ResourceManager.GetString("ExportJXJgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出认证清单失败.
        /// </summary>
        public static string ExportRzqdFail {
            get {
                return ResourceManager.GetString("ExportRzqdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出成功.
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户角色设置失败,请稍候再试！.
        /// </summary>
        public static string FailedSettingUserRole {
            get {
                return ResourceManager.GetString("FailedSettingUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据解锁失败，请刷新页面.
        /// </summary>
        public static string FailedUnLocking {
            get {
                return ResourceManager.GetString("FailedUnLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段不匹配.
        /// </summary>
        public static string FieldMismatch {
            get {
                return ResourceManager.GetString("FieldMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票机号应小于等于6位，只支持数字.
        /// </summary>
        public static string FjhLengthValid {
            get {
                return ResourceManager.GetString("FjhLengthValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票机号不能为空.
        /// </summary>
        public static string FjhNotEmpty {
            get {
                return ResourceManager.GetString("FjhNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票查询异常，请稍后重试.
        /// </summary>
        public static string FpcySearchError {
            get {
                return ResourceManager.GetString("FpcySearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组件接口初始化纳税人识别号:{0} 分机号:{1} 地区编号:{2},返回值:{3}.
        /// </summary>
        public static string FreeToolInitLog {
            get {
                return ResourceManager.GetString("FreeToolInitLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeTool.ocx组件更新失败.
        /// </summary>
        public static string FreeToolOCXUpdateFail {
            get {
                return ResourceManager.GetString("FreeToolOCXUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCX组件传递的参数.
        /// </summary>
        public static string FreeToolParam {
            get {
                return ResourceManager.GetString("FreeToolParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票软件基础包升级异常.
        /// </summary>
        public static string FwkpBaseUpdateError {
            get {
                return ResourceManager.GetString("FwkpBaseUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票软件安装包升级异常：.
        /// </summary>
        public static string FwkpUpdateFailed {
            get {
                return ResourceManager.GetString("FwkpUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现新版本开票软件，启动开票软件时将自动升级.
        /// </summary>
        public static string FwkpUpdateRemind {
            get {
                return ResourceManager.GetString("FwkpUpdateRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取开票软件版本号失败.
        /// </summary>
        public static string FWKPVersionFail {
            get {
                return ResourceManager.GetString("FWKPVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取广告数据异常.
        /// </summary>
        public static string GetAdertiesError {
            get {
                return ResourceManager.GetString("GetAdertiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取常用列表应用失败：.
        /// </summary>
        public static string GetAppFail {
            get {
                return ResourceManager.GetString("GetAppFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取地区编号异常.
        /// </summary>
        public static string GetAreaNoError {
            get {
                return ResourceManager.GetString("GetAreaNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取盒子设备编号异常.
        /// </summary>
        public static string GetBoxDeviceNoError {
            get {
                return ResourceManager.GetString("GetBoxDeviceNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取企业信息失败：.
        /// </summary>
        public static string GetCJFail {
            get {
                return ResourceManager.GetString("GetCJFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取设备编号失败，请将盒子连接后重试！.
        /// </summary>
        public static string GetDeviceError {
            get {
                return ResourceManager.GetString("GetDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取盒子编号失败.
        /// </summary>
        public static string GetDeviceNoError {
            get {
                return ResourceManager.GetString("GetDeviceNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取地区网络地址失败.
        /// </summary>
        public static string GetDqNetLocationError {
            get {
                return ResourceManager.GetString("GetDqNetLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用报文生成失败：.
        /// </summary>
        public static string GetGlobalFailed {
            get {
                return ResourceManager.GetString("GetGlobalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取查验数据异常.
        /// </summary>
        public static string GetInvoiceDataError {
            get {
                return ResourceManager.GetString("GetInvoiceDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页获取IP失败.
        /// </summary>
        public static string GetIPFailed {
            get {
                return ResourceManager.GetString("GetIPFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取进项未勾选认证发票数据异常.
        /// </summary>
        public static string GetJXDataError {
            get {
                return ResourceManager.GetString("GetJXDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取税款所属期异常.
        /// </summary>
        public static string GetJXSkssqError {
            get {
                return ResourceManager.GetString("GetJXSkssqError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取进项提醒月数失败.
        /// </summary>
        public static string GetJXWarnMonthError {
            get {
                return ResourceManager.GetString("GetJXWarnMonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取开票软件路径报错：.
        /// </summary>
        public static string GetKPPathFailed {
            get {
                return ResourceManager.GetString("GetKPPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取Mac地址失败.
        /// </summary>
        public static string GetMacFail {
            get {
                return ResourceManager.GetString("GetMacFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取宽带拨号IP失败.
        /// </summary>
        public static string GetPPPOEFailed {
            get {
                return ResourceManager.GetString("GetPPPOEFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取打印机驱动列表失败：.
        /// </summary>
        public static string GetPrinterFail {
            get {
                return ResourceManager.GetString("GetPrinterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取注册表异常.
        /// </summary>
        public static string GetRegistryFailed {
            get {
                return ResourceManager.GetString("GetRegistryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用{0}接口异常：.
        /// </summary>
        public static string GetResponseException {
            get {
                return ResourceManager.GetString("GetResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用{0}接口失败，接口返回：{1}-{2}.
        /// </summary>
        public static string GetResponseFailed {
            get {
                return ResourceManager.GetString("GetResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用{0}接口成功，接口返回：{1}-{2}.
        /// </summary>
        public static string GetResponseSuccessed {
            get {
                return ResourceManager.GetString("GetResponseSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取认证清单异常.
        /// </summary>
        public static string GetRzqdError {
            get {
                return ResourceManager.GetString("GetRzqdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取扫描仪驱动列表失败：.
        /// </summary>
        public static string GetScannerFail {
            get {
                return ResourceManager.GetString("GetScannerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取税盘信息失败，请检查盒子连接状态后重试.
        /// </summary>
        public static string GetTaxError {
            get {
                return ResourceManager.GetString("GetTaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取税盘信息失败.
        /// </summary>
        public static string GetTaxErrorLog {
            get {
                return ResourceManager.GetString("GetTaxErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在获取税盘信息....
        /// </summary>
        public static string GetTaxInfoTip {
            get {
                return ResourceManager.GetString("GetTaxInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取逾期发票异常.
        /// </summary>
        public static string GetYqyjError {
            get {
                return ResourceManager.GetString("GetYqyjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勾选认证提交异常.
        /// </summary>
        public static string GxrzSubmitError {
            get {
                return ResourceManager.GetString("GxrzSubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在认证，请稍后....
        /// </summary>
        public static string GxrzWait {
            get {
                return ResourceManager.GetString("GxrzWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检测、复制系统关键文件....
        /// </summary>
        public static string InitCheckFile {
            get {
                return ResourceManager.GetString("InitCheckFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制系统关键文件失败.
        /// </summary>
        public static string InitCheckFileError {
            get {
                return ResourceManager.GetString("InitCheckFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检测、安装字体文件....
        /// </summary>
        public static string InitCheckFont {
            get {
                return ResourceManager.GetString("InitCheckFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装字体文件失败.
        /// </summary>
        public static string InitCheckFontFail {
            get {
                return ResourceManager.GetString("InitCheckFontFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人有效期校验....
        /// </summary>
        public static string InitCheckNsrDeadline {
            get {
                return ResourceManager.GetString("InitCheckNsrDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人有效期校验失败.
        /// </summary>
        public static string InitCheckNsrDeadlineFail {
            get {
                return ResourceManager.GetString("InitCheckNsrDeadlineFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前税号已超出使用期限.
        /// </summary>
        public static string InitCheckNsrDeadlineOut {
            get {
                return ResourceManager.GetString("InitCheckNsrDeadlineOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检测、安装系统所需软件....
        /// </summary>
        public static string InitCheckSoft {
            get {
                return ResourceManager.GetString("InitCheckSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装系统所需软件失败.
        /// </summary>
        public static string InitCheckSoftError {
            get {
                return ResourceManager.GetString("InitCheckSoftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取金税盘信息失败，请关闭后重新启动或者手动输入纳税人信息.
        /// </summary>
        public static string InitGetTaxError {
            get {
                return ResourceManager.GetString("InitGetTaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化开票软件失败，请关闭重新启动.
        /// </summary>
        public static string InitKpFail {
            get {
                return ResourceManager.GetString("InitKpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化开票软件....
        /// </summary>
        public static string InitKpSoft {
            get {
                return ResourceManager.GetString("InitKpSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxTool组件初始化异常！.
        /// </summary>
        public static string InitParasError {
            get {
                return ResourceManager.GetString("InitParasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装应用({0})失败：.
        /// </summary>
        public static string InstallAppFail {
            get {
                return ResourceManager.GetString("InstallAppFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器端程序运行出现错误，请联系管理员！.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票金额不能为空.
        /// </summary>
        public static string InvoiceAmountNotEmpty {
            get {
                return ResourceManager.GetString("InvoiceAmountNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票代码不能为空.
        /// </summary>
        public static string InvoiceCodeNotEmpty {
            get {
                return ResourceManager.GetString("InvoiceCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票日期不能为空.
        /// </summary>
        public static string InvoiceDateNotEmpty {
            get {
                return ResourceManager.GetString("InvoiceDateNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票信息采集接口报错：.
        /// </summary>
        public static string InvoiceError {
            get {
                return ResourceManager.GetString("InvoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票号码不能为空.
        /// </summary>
        public static string InvoiceNoNotEmpty {
            get {
                return ResourceManager.GetString("InvoiceNoNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票数据保存数据库异常：.
        /// </summary>
        public static string InvoiceSaveException {
            get {
                return ResourceManager.GetString("InvoiceSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票类型不能为空.
        /// </summary>
        public static string InvoiceTypeNotEmpty {
            get {
                return ResourceManager.GetString("InvoiceTypeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票信息上传异常：.
        /// </summary>
        public static string InvoiceUpException {
            get {
                return ResourceManager.GetString("InvoiceUpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进项税发票管理软件.
        /// </summary>
        public static string JXAppName {
            get {
                return ResourceManager.GetString("JXAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份解析不一致.
        /// </summary>
        public static string JXCertError {
            get {
                return ResourceManager.GetString("JXCertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差额征税：.
        /// </summary>
        public static string KCE {
            get {
                return ResourceManager.GetString("KCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差额征税蓝票报错：扣除额不能小于（{0}）.
        /// </summary>
        public static string KCEError {
            get {
                return ResourceManager.GetString("KCEError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差额征税蓝票报错：扣除额不能为非数字的字符（{0}）.
        /// </summary>
        public static string KCENumberError {
            get {
                return ResourceManager.GetString("KCENumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差额征税红票报错：扣除额不能大于0（{0}）.
        /// </summary>
        public static string KCERedError {
            get {
                return ResourceManager.GetString("KCERedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aisino.Framework.Startup.
        /// </summary>
        public static string KPAppName {
            get {
                return ResourceManager.GetString("KPAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票软件绿化组件已过期，是否下载最新组件.
        /// </summary>
        public static string KpSoftOutDeadline {
            get {
                return ResourceManager.GetString("KpSoftOutDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票软件尚未初始化.
        /// </summary>
        public static string KPStart {
            get {
                return ResourceManager.GetString("KPStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载，请稍候....
        /// </summary>
        public static string LoadingWait {
            get {
                return ResourceManager.GetString("LoadingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录异常.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在登录....
        /// </summary>
        public static string loginWait {
            get {
                return ResourceManager.GetString("loginWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载用户手册失败：{0}.
        /// </summary>
        public static string ManualDownloadFail {
            get {
                return ResourceManager.GetString("ManualDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户手册下载完成，当前版本号：{0}.
        /// </summary>
        public static string ManualDownloadSuccess {
            get {
                return ResourceManager.GetString("ManualDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改注册表自启动失败.
        /// </summary>
        public static string ModifyAutoRunRegeditError {
            get {
                return ResourceManager.GetString("ModifyAutoRunRegeditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改密码异常.
        /// </summary>
        public static string ModifyPwdError {
            get {
                return ResourceManager.GetString("ModifyPwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改注册码异常.
        /// </summary>
        public static string ModifyZcmError {
            get {
                return ResourceManager.GetString("ModifyZcmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动开票软件至系统盘异常.
        /// </summary>
        public static string MoveKpSoftError {
            get {
                return ResourceManager.GetString("MoveKpSoftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在复制开票软件请稍后....
        /// </summary>
        public static string MoveKpSoftTip {
            get {
                return ResourceManager.GetString("MoveKpSoftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统检测到多台开票设备，请只接入您要使用的设备.
        /// </summary>
        public static string MultiTaxDiskError {
            get {
                return ResourceManager.GetString("MultiTaxDiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络异常，请稍候重试.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前为无盘模式，无法进行发票开具.
        /// </summary>
        public static string NoTaxDiskTip {
            get {
                return ResourceManager.GetString("NoTaxDiskTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前为无盘模式，无法使用该应用！.
        /// </summary>
        public static string NoTaxDiskTip2 {
            get {
                return ResourceManager.GetString("NoTaxDiskTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前状态：未连接税盘.
        /// </summary>
        public static string NotConnTaxDisk {
            get {
                return ResourceManager.GetString("NotConnTaxDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在需要导出的发票数据.
        /// </summary>
        public static string NotExistExportData {
            get {
                return ResourceManager.GetString("NotExistExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到公共区，请检查盒子连接状态.
        /// </summary>
        public static string NotFindBox {
            get {
                return ResourceManager.GetString("NotFindBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现税盘，请连接税盘后使用.
        /// </summary>
        public static string NotFindTax {
            get {
                return ResourceManager.GetString("NotFindTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到税盘，请重新插入盒子后重试.
        /// </summary>
        public static string NotFindTaxDisk {
            get {
                return ResourceManager.GetString("NotFindTaxDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码输入不一致.
        /// </summary>
        public static string NotSameNewPwd {
            get {
                return ResourceManager.GetString("NotSameNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码输入不一致.
        /// </summary>
        public static string NotSamePwd {
            get {
                return ResourceManager.GetString("NotSamePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票数据正在上传税局，确认要退出吗？.
        /// </summary>
        public static string NotUploadExitMsg {
            get {
                return ResourceManager.GetString("NotUploadExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企业税号：{0}     开票机号：{1}     地区编号：{2}.
        /// </summary>
        public static string NsrBaseInfo {
            get {
                return ResourceManager.GetString("NsrBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人有效期校验异常：.
        /// </summary>
        public static string NSRDeadlineValidError {
            get {
                return ResourceManager.GetString("NSRDeadlineValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人信息有误.
        /// </summary>
        public static string NsrInfoError {
            get {
                return ResourceManager.GetString("NsrInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人识别号应大于等于6位小于等于20位，支持数字和字母.
        /// </summary>
        public static string NsrLengthValid {
            get {
                return ResourceManager.GetString("NsrLengthValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人信息不能为空.
        /// </summary>
        public static string NsrNotEmpty {
            get {
                return ResourceManager.GetString("NsrNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人不能为空.
        /// </summary>
        public static string NsrsbhNotEmpty {
            get {
                return ResourceManager.GetString("NsrsbhNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纳税人名称不能为空.
        /// </summary>
        public static string NsrsmcNotEmpty {
            get {
                return ResourceManager.GetString("NsrsmcNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCX组件下载成功.
        /// </summary>
        public static string OCXDownSuccess {
            get {
                return ResourceManager.GetString("OCXDownSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子发票助手用户手册打开失败：.
        /// </summary>
        public static string OpenDZFPUserGuid {
            get {
                return ResourceManager.GetString("OpenDZFPUserGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzfsm\DZF.ScanInvoice.exe.
        /// </summary>
        public static string OpenDzfsm {
            get {
                return ResourceManager.GetString("OpenDzfsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票查验用户手册打开失败：.
        /// </summary>
        public static string OpenFPCYUserGuid {
            get {
                return ResourceManager.GetString("OpenFPCYUserGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增值税电子普通发票软件\EIS.Client.exe.
        /// </summary>
        public static string OpenFPZS {
            get {
                return ResourceManager.GetString("OpenFPZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启开票软件失败！.
        /// </summary>
        public static string OpenFwkpFailed {
            get {
                return ResourceManager.GetString("OpenFwkpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启税控盘软件失败！.
        /// </summary>
        public static string OpenSKPSoftFailed {
            get {
                return ResourceManager.GetString("OpenSKPSoftFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户手册打开失败：.
        /// </summary>
        public static string OpenZFTUserGuidError {
            get {
                return ResourceManager.GetString("OpenZFTUserGuidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地区编码应等于6位，只支持数字.
        /// </summary>
        public static string OrgCodeLengthValid {
            get {
                return ResourceManager.GetString("OrgCodeLengthValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地区编号不能为空.
        /// </summary>
        public static string OrgCodeNotEmpty {
            get {
                return ResourceManager.GetString("OrgCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择不超过60张发票.
        /// </summary>
        public static string OutOfFpCount {
            get {
                return ResourceManager.GetString("OutOfFpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入注册码.
        /// </summary>
        public static string PormptInputZcm {
            get {
                return ResourceManager.GetString("PormptInputZcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请设置登录密码.
        /// </summary>
        public static string PormptSetLoginPwd {
            get {
                return ResourceManager.GetString("PormptSetLoginPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入新密码.
        /// </summary>
        public static string PormptSetNewPwd {
            get {
                return ResourceManager.GetString("PormptSetNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入原密码.
        /// </summary>
        public static string PormptSetOldPwd {
            get {
                return ResourceManager.GetString("PormptSetOldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载打印机驱动({0})失败：.
        /// </summary>
        public static string PrintDriverFail {
            get {
                return ResourceManager.GetString("PrintDriverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印认证清单失败.
        /// </summary>
        public static string PrintRzqdError {
            get {
                return ResourceManager.GetString("PrintRzqdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入证书密码.
        /// </summary>
        public static string PromptInputKey {
            get {
                return ResourceManager.GetString("PromptInputKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入纳税人识别号.
        /// </summary>
        public static string PromptInputNsrsbh {
            get {
                return ResourceManager.GetString("PromptInputNsrsbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string PromptInputPwd {
            get {
                return ResourceManager.GetString("PromptInputPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择地区.
        /// </summary>
        public static string PromptSelectArea {
            get {
                return ResourceManager.GetString("PromptSelectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入证书密码.
        /// </summary>
        public static string PwdNotEmpty {
            get {
                return ResourceManager.GetString("PwdNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询开始日期不能大于结束日期.
        /// </summary>
        public static string QueryDateError {
            get {
                return ResourceManager.GetString("QueryDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxTool组件详细查询失败！.
        /// </summary>
        public static string QueryDetailFailed {
            get {
                return ResourceManager.GetString("QueryDetailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxTool组件主查询失败！.
        /// </summary>
        public static string QueryMainFailed {
            get {
                return ResourceManager.GetString("QueryMainFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件-税额不低于输入有误，请检查.
        /// </summary>
        public static string QuerySeError {
            get {
                return ResourceManager.GetString("QuerySeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题不能为空，请输入您的问题.
        /// </summary>
        public static string QuestionEmptyValid {
            get {
                return ResourceManager.GetString("QuestionEmptyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最多输入200个字符，请修改后重新提交.
        /// </summary>
        public static string QuestionLenthErr {
            get {
                return ResourceManager.GetString("QuestionLenthErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题已提交，请等待答复.
        /// </summary>
        public static string QuestionSubmitSuccess {
            get {
                return ResourceManager.GetString("QuestionSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取配置文件失败.
        /// </summary>
        public static string ReadConfigFail {
            get {
                return ResourceManager.GetString("ReadConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取注册表：读取SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\fwkp.exe失败.
        /// </summary>
        public static string ReadRegistryFailed {
            get {
                return ResourceManager.GetString("ReadRegistryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册异常.
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权失败.
        /// </summary>
        public static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奇偶置换异常.
        /// </summary>
        public static string ReserveError {
            get {
                return ResourceManager.GetString("ReserveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置开票软件注册表路径异常.
        /// </summary>
        public static string ResetFwkpRegError {
            get {
                return ResourceManager.GetString("ResetFwkpRegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在进入主界面....
        /// </summary>
        public static string RunClientTip {
            get {
                return ResourceManager.GetString("RunClientTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载打印机驱动({0})失败：.
        /// </summary>
        public static string ScanDriverFail {
            get {
                return ResourceManager.GetString("ScanDriverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在查询，请稍后....
        /// </summary>
        public static string SearchWaitTip {
            get {
                return ResourceManager.GetString("SearchWaitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 认证发票开票日期止未加载完成，请稍后再试.
        /// </summary>
        public static string SelectEndDateNotLoaded {
            get {
                return ResourceManager.GetString("SelectEndDateNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择您要认证的发票.
        /// </summary>
        public static string SelectGXInvoice {
            get {
                return ResourceManager.GetString("SelectGXInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择税款所属期.
        /// </summary>
        public static string SelectSkssq {
            get {
                return ResourceManager.GetString("SelectSkssq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 认证发票开票日期起未加载完成，请稍后再试.
        /// </summary>
        public static string SelectStartDateNotLoaded {
            get {
                return ResourceManager.GetString("SelectStartDateNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置进项提醒月数失败.
        /// </summary>
        public static string SetJXWarnMonthError {
            get {
                return ResourceManager.GetString("SetJXWarnMonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置税控盘注册表路径失败.
        /// </summary>
        public static string SetSkpRegisterError {
            get {
                return ResourceManager.GetString("SetSkpRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看发票明细异常.
        /// </summary>
        public static string ShowInvoiceDetailError {
            get {
                return ResourceManager.GetString("ShowInvoiceDetailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税控开票系统.
        /// </summary>
        public static string SKPMainWindowName {
            get {
                return ResourceManager.GetString("SKPMainWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税控发票开票软件.
        /// </summary>
        public static string SKPMainWindowTitle {
            get {
                return ResourceManager.GetString("SKPMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企业税号：{0}     机器编号：{1} .
        /// </summary>
        public static string SKPNsrInfo {
            get {
                return ResourceManager.GetString("SKPNsrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税款所属期未加载完成，请稍后再试.
        /// </summary>
        public static string SkssqNotLoaded {
            get {
                return ResourceManager.GetString("SkssqNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件升级失败：.
        /// </summary>
        public static string SoftError {
            get {
                return ResourceManager.GetString("SoftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动客户端....
        /// </summary>
        public static string StartClient {
            get {
                return ResourceManager.GetString("StartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动异常.
        /// </summary>
        public static string StartError {
            get {
                return ResourceManager.GetString("StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交失败.
        /// </summary>
        public static string SubmitFail {
            get {
                return ResourceManager.GetString("SubmitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认以上信息无误后请点击确定按钮.
        /// </summary>
        public static string SureInfo {
            get {
                return ResourceManager.GetString("SureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若您已更换税盘，请点击是，将重启重新获取当前税盘信息.
        /// </summary>
        public static string SwitchTaxTip {
            get {
                return ResourceManager.GetString("SwitchTaxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步数据库：.
        /// </summary>
        public static string SyncDataBase {
            get {
                return ResourceManager.GetString("SyncDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步数据库失败.
        /// </summary>
        public static string SyncDataBaseFail {
            get {
                return ResourceManager.GetString("SyncDataBaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在同步客户编码、商品编码.
        /// </summary>
        public static string SyncFwkpBm {
            get {
                return ResourceManager.GetString("SyncFwkpBm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步发票数据异常.
        /// </summary>
        public static string SyncInvoiceDataError {
            get {
                return ResourceManager.GetString("SyncInvoiceDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步金税盘数据至盒子内异常.
        /// </summary>
        public static string SyncJspDataToBoxError {
            get {
                return ResourceManager.GetString("SyncJspDataToBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步客户编码异常.
        /// </summary>
        public static string SyncKhbmError {
            get {
                return ResourceManager.GetString("SyncKhbmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步商品编码异常.
        /// </summary>
        public static string SyncSpbmError {
            get {
                return ResourceManager.GetString("SyncSpbmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金税盘信息有误，请检查.
        /// </summary>
        public static string TaxInfoErrorCheck {
            get {
                return ResourceManager.GetString("TaxInfoErrorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前税号已超出使用期限.
        /// </summary>
        public static string TaxOutDeadline {
            get {
                return ResourceManager.GetString("TaxOutDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接服务器超时.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接服务器超时，请稍候重试！.
        /// </summary>
        public static string TimeOutError {
            get {
                return ResourceManager.GetString("TimeOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载应用({0})失败：.
        /// </summary>
        public static string UninstallAppFail {
            get {
                return ResourceManager.GetString("UninstallAppFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查本机是否已安装该纳税人的开票软件，如已安装，请双击开票软件安装路径—纳税人识别号—uninst.exe卸载软件（开票软件默认安装路径为C:\Program Files (x86)\开票软件）.
        /// </summary>
        public static string UninstallPrompt {
            get {
                return ResourceManager.GetString("UninstallPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该应用正在运行，请关闭应用后卸载.
        /// </summary>
        public static string UninstallTip {
            get {
                return ResourceManager.GetString("UninstallTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始解压缩....
        /// </summary>
        public static string UnzipStart {
            get {
                return ResourceManager.GetString("UnzipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升级应用({0})失败：.
        /// </summary>
        public static string UpdateAppFail {
            get {
                return ResourceManager.GetString("UpdateAppFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升级程序异常终止，是否重试？.
        /// </summary>
        public static string UpdateErrorTip {
            get {
                return ResourceManager.GetString("UpdateErrorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 升级失败，MD5校验不通过.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新OCX组件失败，请重新启动.
        /// </summary>
        public static string UpdateOCXFail {
            get {
                return ResourceManager.GetString("UpdateOCXFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新包MD5验证不通过，已删除.
        /// </summary>
        public static string UpdateSoftFailed {
            get {
                return ResourceManager.GetString("UpdateSoftFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新包版本号{0}已下载成功,路径:{1}.
        /// </summary>
        public static string UpdateSoftSuccessed {
            get {
                return ResourceManager.GetString("UpdateSoftSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功，当前版本号{0}.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传发票异常.
        /// </summary>
        public static string UploadInvoiceError {
            get {
                return ResourceManager.GetString("UploadInvoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51电子发票客户端软件.
        /// </summary>
        public static string ZZSClientName {
            get {
                return ResourceManager.GetString("ZZSClientName", resourceCulture);
            }
        }
    }
}
